services:
  django:
    build: .
    ports:
      - "8000:8000"
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
        # Rebuild the image if compose changes by checking compose.yml
        - action: rebuild
          path: ./compose.yml
        # Rebuild the image if sources change
        - action: rebuild
          path: ./src
    entrypoint: [ "/usr/bin/env", "sh", "/home/ubuntu/entrypoint" ]
    configs:
      - source: django_entrypoint
        target: /home/ubuntu/entrypoint
        mode: 644
    environment:
      DATABASE_HOST: postgres
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://*"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/8000" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

  postgres-loader:
    image: 'postgres:latest'
    depends_on:
      django:
        condition: service_healthy
    entrypoint: >
      sh -c "
        find /docker-entrypoint-initdb.d -iname "*.sql" | while read f
        do
            psql -h postgres -f "${f}"
        done
      "
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

  makemigrations:
    build: .
    entrypoint: [ "python", "manage.py", "makemigrations" ]
    environment:
      DATABASE_HOST: postgres
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://*"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/home/ubuntu/app/src

configs:
  django_entrypoint:
    content: |
      #!/usr/bin/env sh

      python3 manage.py migrate

      export DJANGO_SUPERUSER_EMAIL=admin@example.com
      export DJANGO_SUPERUSER_USERNAME=admin
      export DJANGO_SUPERUSER_PASSWORD=password
      python3 manage.py createsuperuser --noinput

      python3 manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
