services:
  django:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Host the web application on port 8000
    ports:
      - "8000:8000"
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory `src` with the `/home/ubuntu/app/src` directory in the container
        - action: sync
          path: src
          target: /home/ubuntu/app/src
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
    entrypoint: ["/usr/bin/env", "sh", "/home/ubuntu/entrypoint"]
    configs:
      - source: django_entrypoint
        target: /home/ubuntu/entrypoint
        mode: 0644
    environment:
      DATABASE_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

configs:
  django_entrypoint:
    content: |
      #!/usr/bin/env sh

      python3 manage.py migrate

      export DJANGO_SUPERUSER_EMAIL=admin@example.com
      export DJANGO_SUPERUSER_USERNAME=admin
      export DJANGO_SUPERUSER_PASSWORD=password
      python3 manage.py createsuperuser --noinput

      python3 manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
